### ISSUE TITLE
How to make this node work with dashboard using "some hacking"

### ISSUE THREAD

**Issue by CreativeWarlock** [SenseTecnic/node-red-contrib-users#17]
Hi guys,

congrats to this amazing highly requested node!

I've got 2 questions:

1. Are any updates planned to make this node work with dashboard?
2. In your documentation you mention that your node can be theoretically used with the dashboard, "but some hacking will be required." Could you show me how this is done?

Last but not least: If you provide some donation button, I'll gladly donate your hard work. Please let me know.

Regards,
Marcel

**Comment by tedhuang** [comment]
Hi Marcel,

Thank you for your interest but unfortunately there's currently no plans for any additional development of this node.  When I first created it I remember getting it working with the dashboard node by adding a custom code in the node itself that basically enforces the credentials check via the JWT created by this node, quite a hacky solution since it creates a weird coupling of logic between the nodes. It's been a few years since and I no longer have this chunk of code and it probably won't be useful anymore since the Dashboard node has been updated quite a bit. 

I remember talking to the maintainer of the Dashboard node @dceejay years ago for possible integration strategies but I can't seem to find that conversation either. I believe it involved having the dashboard node support some kind of custom authentication middleware/callback as a part of its configuration.

It actually looks like there are [quite a few people](https://discourse.nodered.org/search?q=%20node-red-contrib-users%20%20dashboard) asking for something like this. Maybe you can take look into a possible solution :smile:.

Cheers,

Ted

**Comment by CreativeWarlock** [comment]
Hi Ted,

Alright then. With that rich feature set of Node Red I'm still very happy with what can be established in flows / dashboard ui.
I cannot imagine how many hundreds of hours of programming that would've been if I had it written with Java alone. ;)

But anyways, thanks you for your extensive answer!

Best regards,
Marcel
